In [1]:
!pip install geopandas

Requirement already satisfied: geopandas in c:\users\mchlc\appdata\local\programs\python\python312\lib\site-packages (1.1.2)
Requirement already satisfied: numpy>=1.24 in c:\users\mchlc\appdata\local\programs\python\python312\lib\site-packages (from geopandas) (2.3.5)
Requirement already satisfied: pyogrio>=0.7.2 in c:\users\mchlc\appdata\local\programs\python\python312\lib\site-packages (from geopandas) (0.12.1)
Requirement already satisfied: packaging in c:\users\mchlc\appdata\local\programs\python\python312\lib\site-packages (from geopandas) (21.3)
Requirement already satisfied: pandas>=2.0.0 in c:\users\mchlc\appdata\local\programs\python\python312\lib\site-packages (from geopandas) (2.3.3)
Requirement already satisfied: pyproj>=3.5.0 in c:\users\mchlc\appdata\local\programs\python\python312\lib\site-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in c:\users\mchlc\appdata\local\programs\python\python312\lib\site-packages (from geopandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mchlc\appdata\local\programs\python\python312\lib\site-packages (from pandas>=2.0.0->geopandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\mchlc\appdata\local\programs\python\python312\lib\site-packages (from pandas>=2.0.0->geopandas) (2021.3)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mchlc\appdata\local\programs\python\python312\lib\site-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: certifi in c:\users\mchlc\appdata\local\programs\python\python312\lib\site-packages (from pyogrio>=0.7.2->geopandas) (2021.10.8)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\mchlc\appdata\local\programs\python\python312\lib\site-packages (from packaging->geopandas) (3.0.7)
Requirement already satisfied: six>=1.5 in c:\users\mchlc\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.16.0)

DEPRECATION: Loading egg at c:\users\mchlc\appdata\local\programs\python\python312\lib\site-packages\dcnet-0.0.1-py3.12.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
WARNING: There was an error checking the latest version of pip.

In [11]:
!pip install pyjanitor

Requirement already satisfied: pyjanitor in c:\users\mchlc\anaconda3\lib\site-packages (0.32.23)
Requirement already satisfied: natsort<9,>=8.4.0 in c:\users\mchlc\anaconda3\lib\site-packages (from pyjanitor) (8.4.0)
Requirement already satisfied: pandas-flavor<0.9,>=0.8.1 in c:\users\mchlc\anaconda3\lib\site-packages (from pyjanitor) (0.8.1)
Requirement already satisfied: multipledispatch in c:\users\mchlc\anaconda3\lib\site-packages (from pyjanitor) (0.6.0)
Requirement already satisfied: scipy in c:\users\mchlc\anaconda3\lib\site-packages (from pyjanitor) (1.13.1)
Requirement already satisfied: janitor-rs<0.7,>=0.6.1 in c:\users\mchlc\anaconda3\lib\site-packages (from pyjanitor) (0.6.1)
Requirement already satisfied: pandas>=0.23 in c:\users\mchlc\anaconda3\lib\site-packages (from pandas-flavor<0.9,>=0.8.1->pyjanitor) (2.2.2)
Requirement already satisfied: xarray in c:\users\mchlc\anaconda3\lib\site-packages (from pandas-flavor<0.9,>=0.8.1->pyjanitor) (2023.6.0)
Requirement already satisfied: six in c:\users\mchlc\anaconda3\lib\site-packages (from multipledispatch->pyjanitor) (1.16.0)
Requirement already satisfied: numpy<2.3,>=1.22.4 in c:\users\mchlc\anaconda3\lib\site-packages (from scipy->pyjanitor) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mchlc\anaconda3\lib\site-packages (from pandas>=0.23->pandas-flavor<0.9,>=0.8.1->pyjanitor) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mchlc\anaconda3\lib\site-packages (from pandas>=0.23->pandas-flavor<0.9,>=0.8.1->pyjanitor) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mchlc\anaconda3\lib\site-packages (from pandas>=0.23->pandas-flavor<0.9,>=0.8.1->pyjanitor) (2023.3)
Requirement already satisfied: packaging>=21.3 in c:\users\mchlc\anaconda3\lib\site-packages (from xarray->pandas-flavor<0.9,>=0.8.1->pyjanitor) (24.1)

In [16]:
%%bash

pip install --upgrade pandas pyjanitor

Requirement already satisfied: pandas in c:\users\mchlc\anaconda3\lib\site-packages (2.2.2)
Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: pyjanitor in c:\users\mchlc\anaconda3\lib\site-packages (0.32.23)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mchlc\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mchlc\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\mchlc\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: natsort<9,>=8.4.0 in c:\users\mchlc\anaconda3\lib\site-packages (from pyjanitor) (8.4.0)
Requirement already satisfied: pandas-flavor<0.9,>=0.8.1 in c:\users\mchlc\anaconda3\lib\site-packages (from pyjanitor) (0.8.1)
Requirement already satisfied: multipledispatch in c:\users\mchlc\anaconda3\lib\site-packages (from pyjanitor) (0.6.0)
Requirement already satisfied: scipy in c:\users\mchlc\anaconda3\lib\site-packages (from pyjanitor) (1.13.1)
Requirement already satisfied: janitor-rs<0.7,>=0.6.1 in c:\users\mchlc\anaconda3\lib\site-packages (from pyjanitor) (0.6.1)
Requirement already satisfied: xarray in c:\users\mchlc\anaconda3\lib\site-packages (from pandas-flavor<0.9,>=0.8.1->pyjanitor) (2023.6.0)
Requirement already satisfied: six>=1.5 in c:\users\mchlc\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: packaging>=21.3 in c:\users\mchlc\anaconda3\lib\site-packages (from xarray->pandas-flavor<0.9,>=0.8.1->pyjanitor) (24.1)
Downloading pandas-3.0.2-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 9.7/9.7 MB 27.6 MB/s eta 0:00:00
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\mchlc\anaconda3\Lib\site-packages\~andas'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.37.1 requires pandas<3,>=1.3.0, but you have pandas 3.0.2 which is incompatible.

Successfully installed pandas-3.0.2

In [2]:
import geopandas as gpd
import pandas as pd

c:\Users\mchlc\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
c:\Users\mchlc\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

# This takes `tidied_noncomm_ev.json` and substancially reduces its size (by grouping by polygons.)

In [ ]:
geojson_df = gpd.read_file("../public/20260216_tidied_comm_ev.gpkg")


crs = geojson_df.crs or "EPSG:4326"
def groupIntoArray(group_data):
    if (len(set(group_data)) == 1):
        return list(group_data)[0]
    
    return list(group_data)


geojson_df.drop(["county", "exchange_value_formatted"], inplace=True, axis=1)
geojson_df["area_id"] = geojson_df["area_id"].apply(lambda x: "Fish catch " + str(x))
geojson_df["exchange_value"] = geojson_df["exchange_value"].fillna(-1.0)
x = geojson_df.groupby(["geometry"], as_index=False).agg(groupIntoArray)

# check if it's all good.

new_gdf = gpd.GeoDataFrame(x, geometry="geometry", crs=crs)
#new_gdf.to_file("collapsed_comm_ev.geojson", driver="geoJSON")

new_gdf.to_file("collapsed_comm_ev.geojson", driver="geoJSON")
x

,geometry,year,area_id,county_olelo,species_group,ecosystem_type,exchange_value
0,"MULTIPOLYGON (((-160.5084 21.66031, -160.51124...","[2021, 2021, 2021, 2021, 2021, 2021, 2021, 202...",moku_ID_508,Kauaʻi,"[Deep 7 Bottomfish, Deep 7 Bottomfish, Deep 7 ...","[All Ecosystems, Inshore — Reef, Coastal — Ope...","[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0,..."
1,"MULTIPOLYGON (((-160.37768 21.71885, -160.3760...","[2021, 2021, 2021, 2021, 2021, 2021, 2021, 202...",moku_ID_528,Kauaʻi,"[Deep 7 Bottomfish, Deep 7 Bottomfish, Deep 7 ...","[All Ecosystems, Inshore — Reef, Coastal — Ope...","[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0,..."
2,"MULTIPOLYGON (((-159.86446 21.63944, -159.8728...","[2021, 2021, 2021, 2021, 2021, 2021, 2021, 202...",moku_ID_527,Kauaʻi,"[Deep 7 Bottomfish, Deep 7 Bottomfish, Deep 7 ...","[All Ecosystems, Inshore — Reef, Coastal — Ope...","[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0,..."
3,"MULTIPOLYGON (((-159.87894 21.82071, -159.9919...","[2021, 2021, 2021, 2021, 2021, 2021, 2021, 202...",moku_ID_525,Kauaʻi,"[Deep 7 Bottomfish, Deep 7 Bottomfish, Deep 7 ...","[All Ecosystems, Inshore — Reef, Coastal — Ope...","[476.00999999999976, 0.0, 476.01, -1.0, -1.0, ..."
4,"MULTIPOLYGON (((-160.0365 22.02476, -160.03483...","[2021, 2021, 2021, 2021, 2021, 2021, 2021, 202...",moku_ID_505,Kauaʻi,"[Deep 7 Bottomfish, Deep 7 Bottomfish, Deep 7 ...","[All Ecosystems, Inshore — Reef, Coastal — Ope...","[2816.1989999999987, 0.0, 2816.199, 7496.94000..."
...,...,...,...,...,...,...,...
77,"MULTIPOLYGON (((-155.90602 19.19226, -155.9184...","[2021, 2021, 2021, 2021, 2021, 2021, 2021, 202...",moku_ID_101,Hawaiʻi,"[Deep 7 Bottomfish, Deep 7 Bottomfish, Deep 7 ...","[All Ecosystems, Inshore — Reef, Coastal — Ope...","[21256.284899999988, 0.0, 21256.2849, 5643.280..."
78,"MULTIPOLYGON (((-154.96265 19.7347, -154.95348...","[2021, 2021, 2021, 2021, 2021, 2021, 2021, 202...",moku_ID_106,Hawaiʻi,"[Deep 7 Bottomfish, Deep 7 Bottomfish, Deep 7 ...","[All Ecosystems, Inshore — Reef, Coastal — Ope...","[11222.130099999995, 0.0, 11222.1301, 1724.08,..."
79,"MULTIPOLYGON (((-154.48992 19.66666, -154.4774...","[2021, 2021, 2021, 2021, 2021, 2021, 2021, 202...",moku_ID_126,Hawaiʻi,"[Deep 7 Bottomfish, Deep 7 Bottomfish, Deep 7 ...","[All Ecosystems, Inshore — Reef, Coastal — Ope...","[11939.184999999994, 0.0, 11939.185, 3888.656,..."
80,"MULTIPOLYGON (((-154.95882 19.32454, -154.9588...","[2021, 2021, 2021, 2021, 2021, 2021, 2021, 202...",moku_ID_107,Hawaiʻi,"[Deep 7 Bottomfish, Deep 7 Bottomfish, Deep 7 ...","[All Ecosystems, Inshore — Reef, Coastal — Ope...","[2698.290999999999, 0.0, 2698.291, 192.464, 10..."
81,"MULTIPOLYGON (((-154.68641 19.15721, -154.7138...","[2021, 2021, 2021, 2021, 2021, 2021, 2021, 202...",moku_ID_127,Hawaiʻi,"[Deep 7 Bottomfish, Deep 7 Bottomfish, Deep 7 ...","[All Ecosystems, Inshore — Reef, Coastal — Ope...","[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0,..."

In [ ]:
def is_valid_df(x):
    must_have = {"geometry", "year", "area_id", "county_olelo", "species_group", "ecosystem_type", "exchange_value"}
    current_columns = set(x.columns)

    if (must_have.issubset(current_columns)):
        print("✅ All columns are valid!")
    else:
        print("❌ The following columns are missing: " + str(must_have - current_columns))
        print("We require the following columns: " + str(must_have))
        return False;

    are_rows_valid = True;
    for row in x.index:
        if ((len(x.loc[row, "year"]) == len(x.loc[row, "species_group"])) and (len(x.loc[row, "species_group"]) == len(x.loc[row, "ecosystem_type"])) and (len(x.loc[row, "ecosystem_type"]) == len(x.loc[row, "exchange_value"]))):
            pass
        else:
            print("❌ Row " + str(row) + " is invalid!")
            cols_to_compare = ["year", "species_group", "ecosystem_type", "exchange_value"]
            for col in cols_to_compare:
                print("Length of '" + col + "' is: " + str(len(x.loc[row, col])))
            print("Array lengths mismatch.")
            print("=====")
            are_rows_valid = False;

    if (are_rows_valid):
        print("✅ All rows are valid!")
    else:
        print("❌ Some columns are invalid. See above.")

    return are_rows_valid;

is_valid_df(x)

❌ The following columns are missing: {'hargga'}
We require the following columns: {'year', 'county_olelo', 'geometry', 'area_id', 'exchange_value', 'species_group', 'ecosystem_type', 'hargga'}

False

In [7]:
geojson_set = set(geojson_df["geometry"].unique())
moku_set = set(moku_df["geometry"].unique())
x=geojson_set.intersection(moku_set)
x

set()

In [20]:
geojson_df = gpd.read_file("../public/20260216_tidied_comm_ev.gpkg")
geojson_df

,year,area_id,county,county_olelo,species_group,ecosystem_type,exchange_value,exchange_value_formatted,geometry
0,2021,100,Hawaii,Hawaiʻi,Deep 7 Bottomfish,All Ecosystems,10288.89130,"$10,289","MULTIPOLYGON (((-155.68082 18.91072, -155.6802..."
1,2021,100,Hawaii,Hawaiʻi,Deep 7 Bottomfish,Inshore — Reef,0.00000,$0,"MULTIPOLYGON (((-155.68082 18.91072, -155.6802..."
2,2021,100,Hawaii,Hawaiʻi,Deep 7 Bottomfish,Coastal — Open Ocean,10288.89130,"$10,289","MULTIPOLYGON (((-155.68082 18.91072, -155.6802..."
3,2021,100,Hawaii,Hawaiʻi,Shallow Bottomfish,All Ecosystems,4314.43200,"$4,314","MULTIPOLYGON (((-155.68082 18.91072, -155.6802..."
4,2021,100,Hawaii,Hawaiʻi,Shallow Bottomfish,Inshore — Reef,1188.78720,"$1,189","MULTIPOLYGON (((-155.68082 18.91072, -155.6802..."
...,...,...,...,...,...,...,...,...,...
30745,1997,528,Kauai,Kauaʻi,Pelagics,Inshore — Reef,0.00000,$0,"MULTIPOLYGON (((-160.37768 21.71885, -160.3760..."
30746,1997,528,Kauai,Kauaʻi,Pelagics,Coastal — Open Ocean,33043.77853,"$33,044","MULTIPOLYGON (((-160.37768 21.71885, -160.3760..."
30747,1997,528,Kauai,Kauaʻi,All Species,All Ecosystems,36998.81325,"$36,999","MULTIPOLYGON (((-160.37768 21.71885, -160.3760..."
30748,1997,528,Kauai,Kauaʻi,All Species,Coastal — Open Ocean,36998.81325,"$36,999","MULTIPOLYGON (((-160.37768 21.71885, -160.3760..."
30749,1997,528,Kauai,Kauaʻi,All Species,Inshore — Reef,0.00000,$0,"MULTIPOLYGON (((-160.37768 21.71885, -160.3760..."

# Merge the moku extents data, and subset them with terrestrial.

In [50]:
df = gpd.read_file("../public/mokuextentsdata/mokus_extents.geojson")

crs = df.crs or "EPSG:4326"
def groupIntoArray(group_data):
    if (len(set(group_data)) == 1):
        return list(group_data)[0]
    if (len(set(group_data)) == 0):
        return []
    
    final_list = list(group_data)
    return [x if not x is None else 0 for x in final_list]

df.drop(["fid", "name2", "moku", "island"], inplace=True, axis=1)
x = df.groupby(["geometry"], as_index=False).agg(groupIntoArray)

#marine_df = x.loc[x["realm"] == "Marine"]
terrestrial_df = x.loc[x["realm"] == "Terrestrial"]

terrestrial_df["total_area_km2"] = terrestrial_df.apply(lambda x: sum(x["area_km2"]) / len(set(x["year"])) if len(x["area_km2"]) > 0 else 0, axis=1)

#new_marine = gpd.GeoDataFrame(marine_df, geometry="geometry", crs=crs)
new_terrestrial = gpd.GeoDataFrame(terrestrial_df, geometry="geometry", crs=crs)

new_terrestrial.to_file("../public/mokuextentsdata/20261007_terrestrial_extents_byMoku.geojson", driver="geoJSON", COORDINATE_PRECISION=5)