In [ ]:
!pip install geopandas

In [11]:
!pip install pyjanitor

Requirement already satisfied: pyjanitor in c:\users\mchlc\anaconda3\lib\site-packages (0.32.23)
Requirement already satisfied: natsort<9,>=8.4.0 in c:\users\mchlc\anaconda3\lib\site-packages (from pyjanitor) (8.4.0)
Requirement already satisfied: pandas-flavor<0.9,>=0.8.1 in c:\users\mchlc\anaconda3\lib\site-packages (from pyjanitor) (0.8.1)
Requirement already satisfied: multipledispatch in c:\users\mchlc\anaconda3\lib\site-packages (from pyjanitor) (0.6.0)
Requirement already satisfied: scipy in c:\users\mchlc\anaconda3\lib\site-packages (from pyjanitor) (1.13.1)
Requirement already satisfied: janitor-rs<0.7,>=0.6.1 in c:\users\mchlc\anaconda3\lib\site-packages (from pyjanitor) (0.6.1)
Requirement already satisfied: pandas>=0.23 in c:\users\mchlc\anaconda3\lib\site-packages (from pandas-flavor<0.9,>=0.8.1->pyjanitor) (2.2.2)
Requirement already satisfied: xarray in c:\users\mchlc\anaconda3\lib\site-packages (from pandas-flavor<0.9,>=0.8.1->pyjanitor) (2023.6.0)
Requirement already satisfied: six in c:\users\mchlc\anaconda3\lib\site-packages (from multipledispatch->pyjanitor) (1.16.0)
Requirement already satisfied: numpy<2.3,>=1.22.4 in c:\users\mchlc\anaconda3\lib\site-packages (from scipy->pyjanitor) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mchlc\anaconda3\lib\site-packages (from pandas>=0.23->pandas-flavor<0.9,>=0.8.1->pyjanitor) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mchlc\anaconda3\lib\site-packages (from pandas>=0.23->pandas-flavor<0.9,>=0.8.1->pyjanitor) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mchlc\anaconda3\lib\site-packages (from pandas>=0.23->pandas-flavor<0.9,>=0.8.1->pyjanitor) (2023.3)
Requirement already satisfied: packaging>=21.3 in c:\users\mchlc\anaconda3\lib\site-packages (from xarray->pandas-flavor<0.9,>=0.8.1->pyjanitor) (24.1)

In [16]:
%%bash

pip install --upgrade pandas pyjanitor

Requirement already satisfied: pandas in c:\users\mchlc\anaconda3\lib\site-packages (2.2.2)
Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: pyjanitor in c:\users\mchlc\anaconda3\lib\site-packages (0.32.23)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mchlc\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mchlc\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\mchlc\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: natsort<9,>=8.4.0 in c:\users\mchlc\anaconda3\lib\site-packages (from pyjanitor) (8.4.0)
Requirement already satisfied: pandas-flavor<0.9,>=0.8.1 in c:\users\mchlc\anaconda3\lib\site-packages (from pyjanitor) (0.8.1)
Requirement already satisfied: multipledispatch in c:\users\mchlc\anaconda3\lib\site-packages (from pyjanitor) (0.6.0)
Requirement already satisfied: scipy in c:\users\mchlc\anaconda3\lib\site-packages (from pyjanitor) (1.13.1)
Requirement already satisfied: janitor-rs<0.7,>=0.6.1 in c:\users\mchlc\anaconda3\lib\site-packages (from pyjanitor) (0.6.1)
Requirement already satisfied: xarray in c:\users\mchlc\anaconda3\lib\site-packages (from pandas-flavor<0.9,>=0.8.1->pyjanitor) (2023.6.0)
Requirement already satisfied: six>=1.5 in c:\users\mchlc\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: packaging>=21.3 in c:\users\mchlc\anaconda3\lib\site-packages (from xarray->pandas-flavor<0.9,>=0.8.1->pyjanitor) (24.1)
Downloading pandas-3.0.2-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 9.7/9.7 MB 27.6 MB/s eta 0:00:00
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\mchlc\anaconda3\Lib\site-packages\~andas'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.37.1 requires pandas<3,>=1.3.0, but you have pandas 3.0.2 which is incompatible.

Successfully installed pandas-3.0.2

In [18]:
import geopandas as gpd
import pandas as pd

### This takes `tidied_noncomm_ev.json` and substancially reduces its size (by grouping by polygons.)

In [ ]:
geojson_df = gpd.read_file("../public/20260216_tidied_comm_ev.gpkg")


crs = geojson_df.crs or "EPSG:4326"
def groupIntoArray(group_data):
    if (len(set(group_data)) == 1):
        return list(group_data)[0]
    
    return list(group_data)


geojson_df.drop(["county", "exchange_value_formatted"], inplace=True, axis=1)
geojson_df["area_id"] = geojson_df["area_id"].apply(lambda x: "Fish catch " + str(x))
geojson_df["exchange_value"] = geojson_df["exchange_value"].fillna(-1.0)
x = geojson_df.groupby(["geometry"], as_index=False).agg(groupIntoArray)

# check if it's all good.

new_gdf = gpd.GeoDataFrame(x, geometry="geometry", crs=crs)
#new_gdf.to_file("collapsed_comm_ev.geojson", driver="geoJSON")

new_gdf.to_file("collapsed_comm_ev.geojson", driver="geoJSON")
x

,geometry,year,area_id,county_olelo,species_group,ecosystem_type,exchange_value
0,"MULTIPOLYGON (((-160.5084 21.66031, -160.51124...","[2021, 2021, 2021, 2021, 2021, 2021, 2021, 202...",moku_ID_508,Kauaʻi,"[Deep 7 Bottomfish, Deep 7 Bottomfish, Deep 7 ...","[All Ecosystems, Inshore — Reef, Coastal — Ope...","[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0,..."
1,"MULTIPOLYGON (((-160.37768 21.71885, -160.3760...","[2021, 2021, 2021, 2021, 2021, 2021, 2021, 202...",moku_ID_528,Kauaʻi,"[Deep 7 Bottomfish, Deep 7 Bottomfish, Deep 7 ...","[All Ecosystems, Inshore — Reef, Coastal — Ope...","[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0,..."
2,"MULTIPOLYGON (((-159.86446 21.63944, -159.8728...","[2021, 2021, 2021, 2021, 2021, 2021, 2021, 202...",moku_ID_527,Kauaʻi,"[Deep 7 Bottomfish, Deep 7 Bottomfish, Deep 7 ...","[All Ecosystems, Inshore — Reef, Coastal — Ope...","[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0,..."
3,"MULTIPOLYGON (((-159.87894 21.82071, -159.9919...","[2021, 2021, 2021, 2021, 2021, 2021, 2021, 202...",moku_ID_525,Kauaʻi,"[Deep 7 Bottomfish, Deep 7 Bottomfish, Deep 7 ...","[All Ecosystems, Inshore — Reef, Coastal — Ope...","[476.00999999999976, 0.0, 476.01, -1.0, -1.0, ..."
4,"MULTIPOLYGON (((-160.0365 22.02476, -160.03483...","[2021, 2021, 2021, 2021, 2021, 2021, 2021, 202...",moku_ID_505,Kauaʻi,"[Deep 7 Bottomfish, Deep 7 Bottomfish, Deep 7 ...","[All Ecosystems, Inshore — Reef, Coastal — Ope...","[2816.1989999999987, 0.0, 2816.199, 7496.94000..."
...,...,...,...,...,...,...,...
77,"MULTIPOLYGON (((-155.90602 19.19226, -155.9184...","[2021, 2021, 2021, 2021, 2021, 2021, 2021, 202...",moku_ID_101,Hawaiʻi,"[Deep 7 Bottomfish, Deep 7 Bottomfish, Deep 7 ...","[All Ecosystems, Inshore — Reef, Coastal — Ope...","[21256.284899999988, 0.0, 21256.2849, 5643.280..."
78,"MULTIPOLYGON (((-154.96265 19.7347, -154.95348...","[2021, 2021, 2021, 2021, 2021, 2021, 2021, 202...",moku_ID_106,Hawaiʻi,"[Deep 7 Bottomfish, Deep 7 Bottomfish, Deep 7 ...","[All Ecosystems, Inshore — Reef, Coastal — Ope...","[11222.130099999995, 0.0, 11222.1301, 1724.08,..."
79,"MULTIPOLYGON (((-154.48992 19.66666, -154.4774...","[2021, 2021, 2021, 2021, 2021, 2021, 2021, 202...",moku_ID_126,Hawaiʻi,"[Deep 7 Bottomfish, Deep 7 Bottomfish, Deep 7 ...","[All Ecosystems, Inshore — Reef, Coastal — Ope...","[11939.184999999994, 0.0, 11939.185, 3888.656,..."
80,"MULTIPOLYGON (((-154.95882 19.32454, -154.9588...","[2021, 2021, 2021, 2021, 2021, 2021, 2021, 202...",moku_ID_107,Hawaiʻi,"[Deep 7 Bottomfish, Deep 7 Bottomfish, Deep 7 ...","[All Ecosystems, Inshore — Reef, Coastal — Ope...","[2698.290999999999, 0.0, 2698.291, 192.464, 10..."
81,"MULTIPOLYGON (((-154.68641 19.15721, -154.7138...","[2021, 2021, 2021, 2021, 2021, 2021, 2021, 202...",moku_ID_127,Hawaiʻi,"[Deep 7 Bottomfish, Deep 7 Bottomfish, Deep 7 ...","[All Ecosystems, Inshore — Reef, Coastal — Ope...","[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0, 0.0,..."

In [ ]:
def is_valid_df(x):
    must_have = {"geometry", "year", "area_id", "county_olelo", "species_group", "ecosystem_type", "exchange_value"}
    current_columns = set(x.columns)

    if (must_have.issubset(current_columns)):
        print("✅ All columns are valid!")
    else:
        print("❌ The following columns are missing: " + str(must_have - current_columns))
        print("We require the following columns: " + str(must_have))
        return False;

    are_rows_valid = True;
    for row in x.index:
        if ((len(x.loc[row, "year"]) == len(x.loc[row, "species_group"])) and (len(x.loc[row, "species_group"]) == len(x.loc[row, "ecosystem_type"])) and (len(x.loc[row, "ecosystem_type"]) == len(x.loc[row, "exchange_value"]))):
            pass
        else:
            print("❌ Row " + str(row) + " is invalid!")
            cols_to_compare = ["year", "species_group", "ecosystem_type", "exchange_value"]
            for col in cols_to_compare:
                print("Length of '" + col + "' is: " + str(len(x.loc[row, col])))
            print("Array lengths mismatch.")
            print("=====")
            are_rows_valid = False;

    if (are_rows_valid):
        print("✅ All rows are valid!")
    else:
        print("❌ Some columns are invalid. See above.")

    return are_rows_valid;

is_valid_df(x)

❌ The following columns are missing: {'hargga'}
We require the following columns: {'year', 'county_olelo', 'geometry', 'area_id', 'exchange_value', 'species_group', 'ecosystem_type', 'hargga'}

False

In [7]:
geojson_set = set(geojson_df["geometry"].unique())
moku_set = set(moku_df["geometry"].unique())
x=geojson_set.intersection(moku_set)
x

set()

In [20]:
geojson_df = gpd.read_file("../public/20260216_tidied_comm_ev.gpkg")
geojson_df

,year,area_id,county,county_olelo,species_group,ecosystem_type,exchange_value,exchange_value_formatted,geometry
0,2021,100,Hawaii,Hawaiʻi,Deep 7 Bottomfish,All Ecosystems,10288.89130,"$10,289","MULTIPOLYGON (((-155.68082 18.91072, -155.6802..."
1,2021,100,Hawaii,Hawaiʻi,Deep 7 Bottomfish,Inshore — Reef,0.00000,$0,"MULTIPOLYGON (((-155.68082 18.91072, -155.6802..."
2,2021,100,Hawaii,Hawaiʻi,Deep 7 Bottomfish,Coastal — Open Ocean,10288.89130,"$10,289","MULTIPOLYGON (((-155.68082 18.91072, -155.6802..."
3,2021,100,Hawaii,Hawaiʻi,Shallow Bottomfish,All Ecosystems,4314.43200,"$4,314","MULTIPOLYGON (((-155.68082 18.91072, -155.6802..."
4,2021,100,Hawaii,Hawaiʻi,Shallow Bottomfish,Inshore — Reef,1188.78720,"$1,189","MULTIPOLYGON (((-155.68082 18.91072, -155.6802..."
...,...,...,...,...,...,...,...,...,...
30745,1997,528,Kauai,Kauaʻi,Pelagics,Inshore — Reef,0.00000,$0,"MULTIPOLYGON (((-160.37768 21.71885, -160.3760..."
30746,1997,528,Kauai,Kauaʻi,Pelagics,Coastal — Open Ocean,33043.77853,"$33,044","MULTIPOLYGON (((-160.37768 21.71885, -160.3760..."
30747,1997,528,Kauai,Kauaʻi,All Species,All Ecosystems,36998.81325,"$36,999","MULTIPOLYGON (((-160.37768 21.71885, -160.3760..."
30748,1997,528,Kauai,Kauaʻi,All Species,Coastal — Open Ocean,36998.81325,"$36,999","MULTIPOLYGON (((-160.37768 21.71885, -160.3760..."
30749,1997,528,Kauai,Kauaʻi,All Species,Inshore — Reef,0.00000,$0,"MULTIPOLYGON (((-160.37768 21.71885, -160.3760..."

In [8]:
geojson_df["geometry"].unique()

<GeometryArray>
[<MULTIPOLYGON (((-155.681 18.911, -155.68 18.874, -155.68 18.874, -155.681 1...>,
 <MULTIPOLYGON (((-155.906 19.192, -155.918 19.187, -155.919 19.187, -155.943...>,
 <MULTIPOLYGON (((-155.876 20.094, -155.876 20.094, -155.876 20.094, -155.876...>,
 <MULTIPOLYGON (((-155.57 20.154, -155.564 20.153, -155.549 20.149, -155.549 ...>,
 <MULTIPOLYGON (((-155.074 19.884, -155.074 19.884, -155.076 19.882, -155.089...>,
 <MULTIPOLYGON (((-155.057 19.86, -155.053 19.854, -155.05 19.847, -155.049 1...>,
 <MULTIPOLYGON (((-154.963 19.735, -154.953 19.72, -154.949 19.707, -154.951 ...>,
 <MULTIPOLYGON (((-154.959 19.325, -154.959 19.325, -154.962 19.318, -154.991...>,
 <MULTIPOLYGON (((-155.509 19.129, -155.484 19.096, -155.484 19.096, -155.501...>,
 <MULTIPOLYGON (((-155.68 18.874, -155.68 18.874, -155.667 18.577, -155.681 1...>,
 <MULTIPOLYGON (((-156.089 19.716, -156.078 19.677, -156.074 19.669, -156.073...>,
 <MULTIPOLYGON (((-155.933 20.128, -155.933 20.128, -155.928 20.107, -155.921...>,
 <MULTIPOLYGON (((-155.496 20.437, -155.516 20.337, -155.517 20.333, -155.524...>,
 <MULTIPOLYGON (((-155.333 20.398, -155.303 20.393, -155.251 20.373, -155.234...>,
 <MULTIPOLYGON (((-154.667 19.828, -154.64 19.802, -154.667 19.797, -154.686 ...>,
 <MULTIPOLYGON (((-154.49 19.667, -154.477 19.642, -154.46 19.593, -154.457 1...>,
 <MULTIPOLYGON (((-154.686 19.157, -154.714 19.137, -154.874 19.045, -154.915...>,
 <MULTIPOLYGON (((-155.305 18.844, -155.324 18.824, -155.33 18.81, -155.333 1...>,
 <MULTIPOLYGON (((-156.453 20.636, -156.475 20.632, -156.477 20.649, -156.474...>,
 <MULTIPOLYGON (((-156.607 21.058, -156.589 21.03, -156.589 21.03, -156.589 2...>,
 <MULTIPOLYGON (((-156.607 21.058, -156.595 21.058, -156.58 21.053, -156.572 ...>,
 <MULTIPOLYGON (((-155.941 20.755, -155.941 20.755, -155.964 20.755, -155.979...>,
 <MULTIPOLYGON (((-155.964 20.755, -155.941 20.755, -155.942 20.747, -155.939...>,
 <MULTIPOLYGON (((-156.167 20.624, -156.169 20.588, -156.169 20.588, -156.174...>,
 <MULTIPOLYGON (((-156.518 20.607, -156.514 20.597, -156.511 20.587, -156.501...>,
 <MULTIPOLYGON (((-156.572 20.603, -156.572 20.603, -156.572 20.603, -156.572...>,
 <MULTIPOLYGON (((-157.057 20.909, -157.057 20.909, -157.058 20.909, -157.058...>,
 <MULTIPOLYGON (((-156.774 20.796, -156.778 20.779, -156.785 20.763, -156.798...>,
 <MULTIPOLYGON (((-156.874 21.048, -156.87 21.017, -156.87 21.017, -156.885 2...>,
 <MULTIPOLYGON (((-157.249 21.222, -157.249 21.222, -157.25 21.222, -157.25 2...>,
 <MULTIPOLYGON (((-156.974 21.249, -156.972 21.215, -156.972 21.215, -156.972...>,
 <MULTIPOLYGON (((-156.68 21.168, -156.68 21.168, -156.71 21.158, -156.71 21....>,
 <MULTIPOLYGON (((-156.87 21.017, -156.874 21.048, -156.873 21.048, -156.873 ...>,
 <MULTIPOLYGON (((-156.701 20.852, -156.699 20.849, -156.676 20.821, -156.674...>,
 <MULTIPOLYGON (((-156.607 21.058, -156.607 21.058, -156.614 21.06, -156.631 ...>,
 <MULTIPOLYGON (((-156.365 21.285, -156.363 21.282, -156.333 21.265, -156.316...>,
 <MULTIPOLYGON (((-156 21.182, -155.988 21.171, -155.954 21.148, -155.932 21....>,
 <MULTIPOLYGON (((-155.64 20.748, -155.639 20.734, -155.648 20.697, -155.655 ...>,
 <MULTIPOLYGON (((-156.169 20.588, -156.173 20.468, -156.174 20.387, -156.17 ...>,
 <MULTIPOLYGON (((-156.497 20.186, -156.554 20.175, -156.584 20.172, -156.625...>,
 <MULTIPOLYGON (((-156.573 20.625, -156.573 20.625, -156.579 20.623, -156.59 ...>,
 <MULTIPOLYGON (((-157.079 20.924, -157.087 20.907, -157.088 20.897, -157.087...>,
 <MULTIPOLYGON (((-157.193 21.052, -157.228 21.029, -157.271 21.009, -157.293...>,
 <MULTIPOLYGON (((-157 21.495, -156.98 21.333, -156.98 21.332, -156.974 21.24...>,
 <MULTIPOLYGON (((-156.667 21.492, -156.676 21.333, -156.676 21.241, -156.68 ...>,
 <MULTIPOLYGON (((-157.848 21.284, -157.848 21.284, -157.847 21.284, -157.847...>,
 <MULTIPOLYGON (((-157.963 21.388, -157.963 21.388, -157.963 21.388, -157.963...>,
 <MULTIPOLYGON (((-158.175 21.4, -158.175 21.4, -158.175 21.4, -158.174 21.4,...>,
 <MULTIPOLYGON (((-158.28 21.575, -158.28 21.574, -158.281 21.575, -158.281 2...>,
 <MULTIPOLYGON (((-158.063 21.647, -158.063 21.647, -158.063 21.647, -158.063...>,
 <MULTIPOLYGON (((-157.892 21.677, -157.918 21.649, -157.918 21.649, -157.918...>,
 <MULTIPOLYGON (((-157.891 21.677, -157.888 21.674, -157.883 21.667, -157.881...>,
 <MULTIPOLYGON (((-157.8 21.546, -157.781 21.518, -157.768 21.509, -157.748 2...>,
 <MULTIPOLYGON (((-157.61 21.29, -157.61 21.29, -157.65 21.302, -157.65 21.30...>,
 <MULTIPOLYGON (((-157.61 21.29, -157.641 21.255, -157.652 21.239, -157.664 2...>,
 <MULTIPOLYGON (((-157.937 21.281, -157.937 21.281, -157.937 21.281, -157.937...>,
 <MULTIPOLYGON (((-157.938 21.282, -157.938 21.282, -157.937 21.282, -157.937...>,
 <MULTIPOLYGON (((-158.207 21.38, -158.207 21.38, -158.191 21.362, -158.178 2...>,
 <MULTIPOLYGON (((-158.307 21.588, -158.307 21.588, -158.307 21.588, -158.307...>,
 <MULTIPOLYGON (((-158.198 21.812, -158.093 21.674, -158.09 21.672, -158.09 2...>,
 <MULTIPOLYGON (((-157.922 22.047, -157.838 22.03, -157.827 22.027, -157.807 ...>,
 <MULTIPOLYGON (((-157.672 21.835, -157.671 21.834, -157.668 21.831, -157.667...>,
 <MULTIPOLYGON (((-157.47 21.667, -157.468 21.663, -157.465 21.659, -157.455 ...>,
 <MULTIPOLYGON (((-157.455 21.246, -157.61 21.29, -157.605 21.302, -157.605 2...>,
 <MULTIPOLYGON (((-157.455 21.246, -157.47 21.211, -157.481 21.193, -157.497 ...>,
 <MULTIPOLYGON (((-159.634 21.913, -159.634 21.913, -159.634 21.913, -159.633...>,
 <MULTIPOLYGON (((-159.761 22.16, -159.761 22.16, -159.746 22.152, -159.728 2...>,
 <MULTIPOLYGON (((-159.583 22.221, -159.584 22.221, -159.584 22.22, -159.584 ...>,
 <MULTIPOLYGON (((-159.281 22.202, -159.281 22.202, -159.312 22.182, -159.312...>,
 <MULTIPOLYGON (((-159.376 21.873, -159.399 21.901, -159.399 21.902, -159.399...>,
 <MULTIPOLYGON (((-160.037 22.025, -160.035 22.024, -160.033 22.017, -160.024...>,
 <MULTIPOLYGON (((-160.037 22.025, -160.064 21.999, -160.064 21.999, -160.064...>,
 <MULTIPOLYGON (((-160.508 21.66, -160.511 21.648, -160.514 21.641, -160.52 2...>,
 <MULTIPOLYGON (((-159.376 21.873, -159.333 21.819, -159.329 21.813, -159.213...>,
 <MULTIPOLYGON (((-159.761 22.16, -159.762 22.157, -159.771 22.141, -159.796 ...>,
 <MULTIPOLYGON (((-159.604 22.255, -159.604 22.255, -159.605 22.255, -159.624...>,
 <MULTIPOLYGON (((-159.333 22.557, -159.33 22.555, -159.329 22.555, -159.268 ...>,
 <MULTIPOLYGON (((-159 22.329, -158.999 22.327, -158.998 22.326, -158.997 22....>,
 <MULTIPOLYGON (((-159.879 21.821, -159.992 21.795, -160 21.793, -160.188 21....>,
 <MULTIPOLYGON (((-160.091 22.316, -160.089 22.31, -160.07 22.281, -160.05 22...>,
 <MULTIPOLYGON (((-159.864 21.639, -159.873 21.638, -159.881 21.638, -159.897...>,
 <MULTIPOLYGON (((-160.378 21.719, -160.376 21.716, -160.36 21.686, -160.353 ...>]
Length: 82, dtype: geometry